name: foaming-backend
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Core dependencies with relaxed version constraints
  - blas
  - ca-certificates
  - certifi
  - filelock
  - freetype
  - giflib
  - gmp
  - gmpy2
  - idna
  - jinja2
  - jpeg
  - lcms2
  - libdeflate
  - libffi
  - libgfortran
  - libgfortran5
  - libjpeg-turbo
  - libopenblas
  - libpng
  - libtiff
  - libwebp
  - llvm-openmp
  - lz4-c
  - markupsafe
  - mpc
  - mpfr
  - mpmath
  - ncurses
  - networkx
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - pillow
  - pip
  - pysocks
  - python
  - pytorch
  - torchvision
  - pyyaml
  - readline
  - requests
  - setuptools
  - sqlite
  - sympy
  - tk
  - torchaudio
  - typing_extensions
  - tzdata
  - wheel
  - xz
  - zlib
  - zstd

  # Optional pip packages
  - pip:
      - annotated-types==0.7.0
      - anyio==4.8.0
      - boto3==1.36.6
      - botocore==1.36.6
      - click==8.1.8
      - exceptiongroup==1.2.2
      - fastapi==0.115.7
      - h11==0.14.0
      - jmespath==1.0.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.20
      - s3transfer==0.11.2
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.45.3
      - urllib3==1.26.20
      - uvicorn==0.34.0
